-- DO NOT EDIT. Generated by test_migration_verification_files.
SELECT CAST(IF((SELECT true WHERE EXISTS (SELECT index_name FROM omicron.crdb_internal.table_indexes WHERE descriptor_name = 'rate_limit_policy' AND index_name = 'lookup_rate_limit_policy_by_name')),'true','Schema change verification failed: index lookup_rate_limit_policy_by_name on table rate_limit_policy does not exist') AS BOOL);
